### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by i0x404** [i0x404/mecano_gest#1]
- [ ] Make the number fields in the app take only numbers and if another key is clicked except number then show feedback.
- [ ] Add Dropdown Menu Search
- [ ] Export and Import to CSV
- [ ] Use Flutter shimmer when loading
- [ ] Fix all `catch(e)`
- [ ] Make Reusable UI Components in the App
- [ ] Make UI and Logic separate
- [ ] Make Technician and Product Page use the same Client Card ui
- [ ] Make the app screens to not use the database and model import and instead use the controller import only
